---
title: "Flavors of Cacao"
output:
  html_document:
    keep_md: true
---

# Workbook for the Ggplot lesson

```{r}
# libraries we're going to use
library(tidyverse)
library(ggthemes)
library(janitor)
library(stringr)
library(data.table)

# read in & clean our data
chocolateData <- fread("../input/flavors_of_cacao.csv") %>%
    clean_names() %>% # clean the names
    filter(ref != "REF") # remove the first row (which has no data)
```

# Scatter plot

```{r}
# remove percentage signs from cocoa_percent
chocolateData$cocoa_percent <- parse_number(chocolateData$cocoa_percent)

# automatically detect the types of each column in the data frame
chocolateData <- type_convert(chocolateData)
```

```{r}
ggplot(
  data = chocolateData,
  aes(x = cocoa_percent, y = rating, color = factor(review_date))
) +
  geom_point() +
  geom_smooth(method = 'lm', span = 0.8) + 
  facet_wrap(~ review_date) +
  labs(
    title = "More cocoa leads to lower ratings",
    x = "Cocoa content (percentile)", 
    y = "Rating (1-5)" 
  )
```


# Bar chart

This is @rtatman's cleaning process...

```{r}
# create a column with just the first word of the bean_type() cell
chocolateData$bean_type_simplified <- word(chocolateData$bean_type, 1)
# remove punctuation
chocolateData$bean_type_simplified <- gsub('[[:punct:]]', '', chocolateData$bean_type_simplified)

# get a vector of the names of beans in more than 20 times
commonBeanTypes <- chocolateData %>%
    select(bean_type_simplified) %>%
    group_by(bean_type_simplified) %>%
    count() %>%
    filter(n > 20) %>%
    select(bean_type_simplified)

# subset of the dataset with only chocolate bars made using common beans
chocolateData_commonBeans <- chocolateData %>%
    filter(bean_type_simplified %in% commonBeanTypes$bean_type_simplified)
```

The simplest plot...

```{r}
ggplot(
  data = chocolateData_commonBeans,
  aes(x = bean_type_simplified)
) + geom_bar()
```



```{r}
ggplot(
  data = chocolateData_commonBeans,
  aes(x = bean_type_simplified, fill = bean_type_simplified)
) +
  geom_bar() +
  scale_y_log10() + 
  facet_wrap(~ company_location, dir = 'v')
```
This graphic is beyond horrible, though.

# Line charts

```{r}
# get the mean chocolate rating by year 
meanRatingByYear <- chocolateData %>%
    group_by(review_date) %>%
    summarise(rating = mean(rating))
```

```{r}
meanPlot <- ggplot(
  data = meanRatingByYear,
  aes(x = review_date, y = rating)
) +
  geom_line() +
  geom_smooth(method = 'lm')
```

Theme 1
```{r}
meanPlot + theme_solarized()
```

Theme 2
```{r}
meanPlot + theme_few()
```

